name: CI
on: [push, pull_request]
jobs:
  build:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >> ~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Echo Host Setting
        run: cat ~/.ssh/config
      - name: Check out the source
        run: ssh -oHostKeyAlgorithms=+ssh-rsa -t staging 'cd ~/one.ipwebsolutions.com/wp-content/plugins/scw-table-booking-pro && git pull'
